fail_fast: false
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
        args: ["--maxkb=600"]
      - id: check-case-conflict
      - id: check-toml
      - id: check-xml
      - id: check-yaml
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]

  # Ruff: linter, import sorter, autoflake, pyupgrade replacement
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.13.3
    hooks:
      - id: ruff
        args:
          - --fix
          - --target-version=py310
        types_or:
          - python
          - pyi
      - id: ruff-format
        args:
          - --line-length=100
          - --target-version=py310
        types_or:
          - python
          - pyi

ci:
  autofix_prs: true
  autoupdate_schedule: quarterly
